/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package climatedatareader;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.simple.JSONArray;
import org.json.simple.JSONValue;

/**
 *
 * @author Anibal
 */
public class ClimateDataReaderImpl extends ClimateDataReader{
    
    /**
     *
     * @return
     */
    @Override
    public JSONArray readJsonClimate() {
        
        InputStream is;
        //try {
               /* is = new FileInputStream("weather.json");
                BufferedReader buf = new BufferedReader(new InputStreamReader(is));

                String line = buf.readLine();
                StringBuilder sb = new StringBuilder();

                while(line != null){
                   sb.append(line).append("\n");
                   line = buf.readLine();
                }

                String inputLine = sb.toString(); */
                String json = 
                        "[\n"+
                            "{\"_id\":\"5bbbc222cc250c03677a095a\",\"dist\":12.15,\"lid\":1795,\"fid\":1795,\"int_number\":87852,\"name\":\"Perito Moreno\",\"province\":\"Santa Cruz\",\"lat\":\"-46.59955597\",\"lon\":\"-70.91318512\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":38,\"pressure\":955,\"st\":null,\"visibility\":50,\"wind_speed\":33,\"id\":2,\"description\":\"Parcialmente nublado\",\"temp\":16.6,\"wing_deg\":\"Oeste\",\"tempDesc\":\"16.6ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d47076a\",\"timestamp\":\"1607430602643\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":1795,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":8,\"radiation\":null,\"morning\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos moderados del noroeste. \"},\"afternoon\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos moderados del noroeste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":0,\"temp_max\":11,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos leves a moderados o regulares del secor oeste con ráfagas. \"},\"afternoon\":{\"weather_id\":15,\"description\":\"Nubosidad variable. Vientos regulares a moderados del sector oeste.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":2,\"temp_max\":14,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":4,\"temp_max\":15,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":10,\"description\":\"Nublado\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":3,\"temp_max\":12,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a095c\",\"dist\":10.59,\"lid\":137,\"fid\":137,\"int_number\":87765,\"name\":\"San Carlos de Bariloche\",\"province\":\"Río Negro\",\"lat\":\"-41.15048981\",\"lon\":\"-71.29316711\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":67,\"pressure\":920.2,\"st\":null,\"visibility\":10,\"wind_speed\":38,\"id\":3,\"description\":\"Parcialmente nublado con lluvia en la hora anterior\",\"temp\":10.4,\"wing_deg\":\"Oeste\",\"tempDesc\":\"10.4ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d470755\",\"timestamp\":\"1607430602611\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":137,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":8,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo lgo o parcialmente nublado. Vientos leves del sector oeste. \"},\"afternoon\":{\"weather_id\":2,\"description\":\"Cielo lgo o parcialmente nublado. Vientos leves del sector oeste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":0,\"temp_max\":13,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo parcialmente nublado Vientos leves o moderados del sector oeste.\"},\"afternoon\":{\"weather_id\":13,\"description\":\"Cielo parcialmente nublado o nublado. Probabilidad de lluvias y lloviznas. Vientos leves del sector sur.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":2,\"temp_max\":12,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":12,\"description\":\"Inestable\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":4,\"temp_max\":12,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":3,\"temp_max\":14,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":2,\"description\":\"Parcialmente nublado\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a095e\",\"dist\":17.56,\"lid\":1840,\"fid\":1840,\"int_number\":87904,\"name\":\"El Calafate\",\"province\":\"Santa Cruz\",\"lat\":\"-50.34061394\",\"lon\":\"-72.26842674\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":92,\"pressure\":980.1,\"st\":null,\"visibility\":15,\"wind_speed\":11,\"id\":3,\"description\":\"Nublado con lluvia\",\"temp\":11.2,\"wing_deg\":\"Oeste\",\"tempDesc\":\"11.2ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d470782\",\"timestamp\":\"1607430602679\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":1840,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":7,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo parcialmente nublado. Vientos leves a moderados del noroeste.\"},\"afternoon\":{\"weather_id\":2,\"description\":\"Cielo parcialmente nublado. Vientos leves a moderados del noroeste.\"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":-2,\"temp_max\":11,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Cielo nublado. Probabilidad de lluvias aisladas. Vientos regulares del sudoeste con ráfagas.\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Nubosidad en disminución. Vientos leves del sector oeste.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":1,\"temp_max\":13,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":0,\"temp_max\":8,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":10,\"description\":\"Nublado\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":0,\"temp_max\":10,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":12,\"description\":\"Inestable\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0961\",\"dist\":2.7,\"lid\":1865,\"fid\":1865,\"int_number\":87912,\"name\":\"Puerto Santa Cruz\",\"province\":\"Santa Cruz\",\"lat\":\"-50.02256012\",\"lon\":\"-68.52765656\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":67,\"pressure\":988.2,\"st\":null,\"visibility\":10,\"wind_speed\":27,\"id\":10,\"description\":\"Nublado con lluvia en la hora anterior\",\"temp\":15.4,\"wing_deg\":\"Norte\",\"tempDesc\":\"15.4ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d470792\",\"timestamp\":\"1607430602719\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":1865,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":7,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos moderados del noroeste. \"},\"afternoon\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos moderados del noroeste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":3,\"temp_max\":12,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Cielo nublado. Probabilidad de lluvias aisladas. Vientos leves del noroeste cambiando a moderados del sudoeste.\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Cielo nublado a parcialmente nublado.Probabilidad de lluvias aisladas. Mejorando. Vientos regulares a moderados del sudoeste con ráfagas. \"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":1,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Parcialmente nublado\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":3,\"temp_max\":12,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":10,\"description\":\"Nublado\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":2,\"temp_max\":13,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0962\",\"dist\":4.25,\"lid\":1868,\"fid\":1868,\"int_number\":87925,\"name\":\"Río Gallegos\",\"province\":\"Santa Cruz\",\"lat\":\"-51.61967087\",\"lon\":\"-69.22193909\",\"zoom\":\"1\",\"updated\":1607432400,\"weather\":{\"humidity\":74,\"pressure\":999.8,\"st\":null,\"visibility\":30,\"wind_speed\":22,\"id\":10,\"description\":\"Nublado\",\"temp\":14.6,\"wing_deg\":\"Este\",\"tempDesc\":\"14.6ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d470781\",\"timestamp\":\"1607430602677\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":1868,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":6,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos moderados del noroeste. \"},\"afternoon\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos moderados del noroeste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":0,\"temp_max\":9,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Cielo nublado. Probabilidad de lluvias aisladas. Vientos leves del noroeste cambiando a moderados del sudoeste.\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Cielo nublado a parcialmente nublado.Probabilidad de lluvias aisladas. Mejorando. Vientos regulares a moderados del sudoeste con ráfagas. \"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":1,\"temp_max\":13,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":1,\"temp_max\":9,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":1,\"temp_max\":11,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":12,\"description\":\"Inestable\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0965\",\"dist\":6.65,\"lid\":1827,\"fid\":1827,\"int_number\":87880,\"name\":\"Gobernador Gregores\",\"province\":\"Santa Cruz\",\"lat\":\"-48.7517395\",\"lon\":\"-70.24363708\",\"zoom\":\"2\",\"updated\":1607428800,\"weather\":{\"humidity\":46,\"pressure\":959.5,\"st\":null,\"visibility\":45,\"wind_speed\":27,\"id\":2,\"description\":\"Parcialmente nublado\",\"temp\":17,\"wing_deg\":\"Sudoeste\",\"tempDesc\":\"17ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d47076f\",\"timestamp\":\"1607430602650\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":1827,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":9,\"radiation\":null,\"morning\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos moderados del noroeste. \"},\"afternoon\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos moderados del noroeste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":0,\"temp_max\":10,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos leves a moderados o regulares del secor oeste con ráfagas. \"},\"afternoon\":{\"weather_id\":15,\"description\":\"Nubosidad variable. Vientos regulares a moderados del sector oeste.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":4,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":3,\"temp_max\":14,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":10,\"description\":\"Nublado\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":4,\"temp_max\":14,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":20,\"description\":\"Ventoso\"},\"afternoon\":{\"weather_id\":20,\"description\":\"Ventoso\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a097f\",\"dist\":10.98,\"lid\":3833,\"fid\":3833,\"int_number\":87596,\"name\":\"Punta Indio\",\"province\":\"Buenos Aires\",\"lat\":\"-35.27056885\",\"lon\":\"-57.25535583\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":69,\"pressure\":1015.9,\"st\":null,\"visibility\":10,\"wind_speed\":18,\"id\":1,\"description\":\"Algo nublado\",\"temp\":22.6,\"wing_deg\":\"Noreste\",\"tempDesc\":\"22.6ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d4707c6\",\"timestamp\":\"1607430602793\",\"date_time\":\"2019-05-08 17:30\",\"location_id\":3833,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":17,\"radiation\":null,\"morning\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos  leves del sector este.\"},\"afternoon\":{\"weather_id\":2,\"description\":\"Cielo algo a parcialmente nublado. Vientos  leves del sector este.\"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":15,\"temp_max\":18,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":18,\"description\":\"Cielo parcialmente nublado a nublado. Probabilidad neblinas especialmente en la zona suburbana. Tiempo desmejorando,  con probabilidad de lluvias  y algunas tormentas. Vientos moderados del sector este.\"},\"afternoon\":{\"weather_id\":4,\"description\":\"Cielo nublado. Probabilidad de lluvias y tormentas. Vientos   leves del sector este.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":14,\"temp_max\":20,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":4,\"description\":\"Nubosidad variable. Probabilidad de lluvias y algunas tormentas.  Mejorando temporariamente. Vientos leves del sector oeste,  cambiando a moderados del sudoeste,  con ráfagas.  \"},\"afternoon\":{\"weather_id\":11,\"description\":\"Nubosidad variable. Probabilidad chaparrones. Vientos moderados a leves  del sudoeste.\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":9,\"temp_max\":18,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":1,\"description\":\"Cielo parcial a algo nublado. Vientos leves del sudoeste. \"},\"afternoon\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos leves del sector oeste. \"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":11,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos leves del sector oeste. \"},\"afternoon\":{\"weather_id\":1,\"description\":\"Cielo algo nublado. Vientos leves del sector oeste. \"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0b17\",\"dist\":10.58,\"lid\":10118,\"fid\":10118,\"int_number\":87121,\"name\":\"San Miguel de Tucumán\",\"province\":\"Tucumán\",\"lat\":\"-26.82396126\",\"lon\":\"-65.20252991\",\"zoom\":\"1\",\"updated\":1607432400,\"weather\":{\"humidity\":64,\"pressure\":961,\"st\":null,\"visibility\":15,\"wind_speed\":7,\"id\":1,\"description\":\"Algo nublado\",\"temp\":24.6,\"wing_deg\":\"Sudoeste\",\"tempDesc\":\"24.6ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d4707d7\",\"timestamp\":\"1607430602837\",\"date_time\":\"2019-05-08 18:00\",\"location_id\":10118,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":null,\"temp_max\":null,\"temp_min_sub\":null,\"temp_noc\":20,\"radiation\":null,\"morning\":{\"weather_id\":13,\"description\":\"Cielo nublado. Probabilidad de lluvias y lloviznas. Vientos leves del noreste.\"},\"afternoon\":{\"weather_id\":13,\"description\":\"Cielo nublado. Probabilidad de lluvias y lloviznas. Vientos leves del noreste.\"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":17,\"temp_max\":25,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":14,\"description\":\"Probables neblinas y bancos de niebla. Nubosidad variable. Probabilidad de lluvias y algunos chaparrones. Vientos leves del noreste.\"},\"afternoon\":{\"weather_id\":14,\"description\":\"Nubosidad variable. Probabilidad de lluvias y algunas tormentas. Vientos leves del noreste.\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":16,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":12,\"description\":\"Inestable\"},\"afternoon\":{\"weather_id\":15,\"description\":\"Nubosidad variable\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":12,\"temp_max\":20,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":15,\"description\":\"Nubosidad variable\"},\"afternoon\":{\"weather_id\":1,\"description\":\"Algo nublado\"}},\"4\":{\"date\":\"2019-05-12\",\"temp_min\":12,\"temp_max\":22,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":1,\"description\":\"Algo nublado\"},\"afternoon\":{\"weather_id\":1,\"description\":\"Algo nublado\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0988\",\"dist\":57.96,\"lid\":4144,\"fid\":4144,\"int_number\":87648,\"name\":\"Maipú\",\"province\":\"Buenos Aires\",\"lat\":\"-36.85823822\",\"lon\":\"-57.87769699\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":68,\"pressure\":1017.2,\"st\":null,\"visibility\":10,\"wind_speed\":18,\"id\":1,\"description\":\"Algo nublado\",\"temp\":23.4,\"wing_deg\":\"Norte\",\"tempDesc\":\"23.4ºC\"},\"forecast\":{\"_id\":\"598b8720f9a90f9a3d4707fe\",\"timestamp\":\"1557349823343\",\"date_time\":\"2019-05-08 06:00\",\"location_id\":4144,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":10,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":15,\"description\":\"Neblinas y bancos de niebla. Nubosidad variable. Vientos leves a moderados del noreste. \"},\"afternoon\":{\"weather_id\":2,\"description\":\"Nubosidad variable. Vientos moderados del noreste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":10,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":12,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":4,\"description\":\"Lluvias y tormentas\"},\"afternoon\":{\"weather_id\":3,\"description\":\"Lluvias\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":5,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a0989\",\"dist\":5.59,\"lid\":4129,\"fid\":4129,\"int_number\":87563,\"name\":\"Las Flores\",\"province\":\"Buenos Aires\",\"lat\":\"-36.01638794\",\"lon\":\"-59.10038376\",\"zoom\":\"2\",\"updated\":1607428800,\"weather\":{\"humidity\":62,\"pressure\":1012.6,\"st\":null,\"visibility\":15,\"wind_speed\":11,\"id\":1,\"description\":\"Algo nublado\",\"temp\":21.2,\"wing_deg\":\"Noroeste\",\"tempDesc\":\"21.2ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d4707bb\",\"timestamp\":\"1557349823265\",\"date_time\":\"2019-05-08 06:00\",\"location_id\":4129,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":10,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Nubosidad variable. Neblinas y nieblas. Probabilidad de lluvias aisladas. Mejorando. Vientos leves del sector este rotando al noreste y aumentando a moderados. \"},\"afternoon\":{\"weather_id\":15,\"description\":\"Neblinas. Nubosidad variable. Vientos moderados a leves del noreste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":9,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":11,\"temp_max\":15,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":4,\"description\":\"Lluvias y tormentas\"},\"afternoon\":{\"weather_id\":3,\"description\":\"Lluvias\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":2,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a098b\",\"dist\":90.48,\"lid\":4153,\"fid\":4153,\"int_number\":87648,\"name\":\"San Clemente del Tuyú\",\"province\":\"Buenos Aires\",\"lat\":\"-36.35927582\",\"lon\":\"-56.72302246\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":68,\"pressure\":1017.2,\"st\":null,\"visibility\":10,\"wind_speed\":18,\"id\":1,\"description\":\"Algo nublado\",\"temp\":23.4,\"wing_deg\":\"Norte\",\"tempDesc\":\"23.4ºC\"},\"forecast\":{\"_id\":\"598b8720f9a90f9a3d4707fc\",\"timestamp\":\"1557349823341\",\"date_time\":\"2019-05-08 06:00\",\"location_id\":4153,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":5,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Nubosidad variable. Neblinas y nieblas. Probabilidad de lluvias aisladas. Mejorando. Vientos leves del sector este rotando al noreste y aumentando a moderados. \"},\"afternoon\":{\"weather_id\":15,\"description\":\"Neblinas. Nubosidad variable. Vientos moderados a leves del noreste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":12,\"temp_max\":19,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":13,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":4,\"description\":\"Lluvias y tormentas\"},\"afternoon\":{\"weather_id\":3,\"description\":\"Lluvias\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":5,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}}}}},\n" +
                            "{\"_id\":\"5bbbc222cc250c03677a098d\",\"dist\":13.05,\"lid\":4265,\"fid\":4265,\"int_number\":87645,\"name\":\"Tandil\",\"province\":\"Buenos Aires\",\"lat\":\"-37.31096268\",\"lon\":\"-59.13938522\",\"zoom\":\"2\",\"updated\":1607432400,\"weather\":{\"humidity\":55,\"pressure\":996.5,\"st\":null,\"visibility\":20,\"wind_speed\":20,\"id\":1,\"description\":\"Algo nublado\",\"temp\":22.7,\"wing_deg\":\"Norte\",\"tempDesc\":\"22.7ºC\"},\"forecast\":{\"_id\":\"598b871ff9a90f9a3d4707a8\",\"timestamp\":\"1557349823245\",\"date_time\":\"2019-05-08 06:00\",\"location_id\":4265,\"forecast\":{\"0\":{\"date\":\"2019-05-08\",\"temp_min\":9,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Nubosidad variable. Neblinas y nieblas. Probabilidad de lluvias aisladas. Mejorando. Vientos leves del sector este rotando al noreste y aumentando a moderados. \"},\"afternoon\":{\"weather_id\":15,\"description\":\"Neblinas. Nubosidad variable. Vientos moderados a leves del noreste. \"}},\"1\":{\"date\":\"2019-05-09\",\"temp_min\":7,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":10,\"description\":\"Nublado\"},\"afternoon\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"}},\"2\":{\"date\":\"2019-05-10\",\"temp_min\":9,\"temp_max\":17,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":4,\"description\":\"Lluvias y tormentas\"},\"afternoon\":{\"weather_id\":3,\"description\":\"Lluvias\"}},\"3\":{\"date\":\"2019-05-11\",\"temp_min\":4,\"temp_max\":16,\"temp_min_sub\":null,\"temp_noc\":null,\"radiation\":null,\"morning\":{\"weather_id\":11,\"description\":\"Inestable con probables precipitaciones\"},\"afternoon\":{\"weather_id\":12,\"description\":\"Inestable\"}}}}}\n" +
                        "]";                        
                Object obj = JSONValue.parse(json);
                return (JSONArray) obj;
            
        /*} catch (IOException ex) {
            Logger.getLogger(ClimateDataReaderImpl.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        //return null;
    }
    
}
